//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deneme_entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WaterWayContext : DbContext
    {
        public WaterWayContext()
            : base("name=WaterWayContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Adres> Adres { get; set; }
        public virtual DbSet<Müsteri> Müsteri { get; set; }
        public virtual DbSet<Siparis> Siparis { get; set; }
        public virtual DbSet<Sirket> Sirket { get; set; }
        public virtual DbSet<SirketAdres> SirketAdres { get; set; }
        public virtual DbSet<SirketUrun> SirketUrun { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Urun> Urun { get; set; }
        public virtual DbSet<SiparisUrun> SiparisUrun { get; set; }
    }
}
