//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deneme_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        public int SiparisID { get; set; }
        public Nullable<System.DateTime> SiparisZamani { get; set; }
        public Nullable<System.DateTime> TeslimZamani { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<decimal> SiparisTutar { get; set; }
    
        public virtual Müsteri Müsteri { get; set; }
        public virtual SiparisUrun SiparisUrun { get; set; }
    }
}
