//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deneme_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SirketUrun
    {
        public int SirketID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public int SirketUrunID { get; set; }
    
        public virtual Sirket Sirket { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
