//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deneme_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sirket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sirket()
        {
            this.SirketUrun = new HashSet<SirketUrun>();
        }
    
        public int SirketID { get; set; }
        public string SirketAdi { get; set; }
        public string Mail { get; set; }
        public string Parola { get; set; }
        public Nullable<int> SirketAdresID { get; set; }
    
        public virtual SirketAdres SirketAdres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SirketUrun> SirketUrun { get; set; }
    }
}
